server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tpvuser
    username: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://tpv-user
          jwk-set-uri: http://localhost:8081/oauth2/jwks

springdoc:
  swagger-ui:
    oauth:
      client-id: client-id
      client-secret: client-secret
